micronaut:
  application:
    name: casaDoCodigo
datasources:
  default:
    url: ${DB_URL:`jdbc:mysql://localhost:3306/cdc?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
endpoints:
  api:
    viacep: https://viacep.com.br/ws