datasources:
  default:
    url: ${DB_URL:`jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE`}
    driverClassName: org.h2.Driver
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:''}
    dialect: H2
logger:
  levels:
    io.micronaut.transaction: DEBUG